Repository Revature-Leafbound/Leafbound, pull requests merged in 2022-06, with the labels that each got.

#5 Create: Registration Page
  angular.json
  documents/FrontEndStyles/Front_End_Resources.md
  documents/FrontEndStyles/images/examplestyleguide.jpg
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/register/register.component.css
  src/app/components/register/register.component.html
  src/app/components/register/register.component.spec.ts
  src/app/components/register/register.component.ts
  src/app/models/user.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/index.html
  src/styles.css
Labels: register

#15 generated user-profile component
  src/app/app.module.ts
  src/app/user-profile/user-profile.component.css
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.spec.ts
  src/app/user-profile/user-profile.component.ts
Labels: feature

#26 13 feature profile
  .vscode/extensions.json
  src/app/components/order-history/order-history.component.css
  src/app/components/order-history/order-history.component.html
  src/app/components/order-history/order-history.component.spec.ts
  src/app/components/order-history/order-history.component.ts
  src/app/components/user-profile/user-profile.component.css
  src/app/components/user-profile/user-profile.component.html
  src/app/components/user-profile/user-profile.component.spec.ts
  src/app/components/user-profile/user-profile.component.ts
  src/app/models/order.ts
  src/app/services/order.service.spec.ts
  src/app/services/order.service.ts
Labels: order history

#34 Added README.md and STARTUP.md
  README.md
  STARTUP.md
Labels: documentation

#29 Cart UI 2
  angular.json
  documents/FrontEndStyles/Front_End_Resources.md
  documents/FrontEndStyles/images/examplestyleguide.jpg
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/checkout.css
  src/app/checkout.html
  src/app/checkout.ts
  src/app/components/cart/cart.component.css
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.spec.ts
  src/app/components/cart/cart.component.ts
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/app/components/register/register.component.css
  src/app/components/register/register.component.html
  src/app/components/register/register.component.spec.ts
  src/app/components/register/register.component.ts
  src/app/models/cart.model.spec.ts
  src/app/models/cart.model.ts
  src/app/models/user.ts
  src/app/routing/routing.module.ts
  src/app/services/cart.service.spec.ts
  src/app/services/cart.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/app/user-profile/user-profile.component.css
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.spec.ts
  src/app/user-profile/user-profile.component.ts
  src/assets/images/logo.svg
  src/assets/images/logo2.svg
  src/index.html
  src/material.module.ts
  src/styles.css
  src/theme.scss
Labels: feature
